// build-site.mjs — turns site/index.src.html into the deployable site/index.html.
//
//   node engine/build-site.mjs
//
// Three jobs:
//   1. Render every piece of TeX with KaTeX, at build time, so the page ships
//      no maths JavaScript at all.
//   2. Vendor the KaTeX stylesheet and the woff2 faces it actually uses, so the
//      page depends on no third-party host and works offline.
//   3. Emit site/sim-core.js from engine/model.mjs, so that the browser runs
//      exactly the equations the published figures were generated from and
//      there is only ever one copy of the model.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, copyFileSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import katex from 'katex';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = join(ROOT, 'site');

// ---------------------------------------------------------------------------
// 1. sim-core.js
// ---------------------------------------------------------------------------

{
  const src = readFileSync(join(ROOT, 'engine', 'model.mjs'), 'utf8');
  const body = src.replace(/^export\s+/gm, '');
  const out = `/* sim-core.js — GENERATED from engine/model.mjs by engine/build-site.mjs.
   Do not edit this file: edit the model and rebuild. It is the same code the
   published figures were generated from, exposed as a global so that it can be
   loaded both by a classic worker (importScripts) and by the page itself. */

(function (global) {
'use strict';

${body}

global.SimCore = {
  makeRng, expo, TABLE_2_1, UNPUBLISHED, defaultParams, Market,
  EVENT_LABELS, EVENT_SYMBOLS,
};
})(typeof self !== 'undefined' ? self : this);
`;
  writeFileSync(join(SITE, 'sim-core.js'), out);
  console.log(`sim-core.js  ${(out.length / 1024).toFixed(1)} KB`);
}

// ---------------------------------------------------------------------------
// 2. KaTeX assets
// ---------------------------------------------------------------------------

{
  const dist = join(ROOT, 'node_modules', 'katex', 'dist');
  const dest = join(SITE, 'vendor', 'katex');
  mkdirSync(join(dest, 'fonts'), { recursive: true });

  // Only the woff2 faces are kept; the ttf and woff fallbacks would triple the
  // weight for browsers that have not needed them for a decade. The @font-face
  // rules are rewritten to match.
  let css = readFileSync(join(dist, 'katex.min.css'), 'utf8');
  css = css.replace(/,url\((fonts\/[^)]+\.woff)\)format\("woff"\)/g, '');
  css = css.replace(/,url\((fonts\/[^)]+\.ttf)\)format\("truetype"\)/g, '');
  writeFileSync(join(dest, 'katex.min.css'), css);

  // KaTeX is MIT-licensed; vendoring it carries the obligation to ship the
  // licence alongside it.
  copyFileSync(join(dist, '..', 'LICENSE'), join(dest, 'LICENSE'));

  let n = 0, bytes = 0;
  for (const f of readdirSync(join(dist, 'fonts'))) {
    if (!f.endsWith('.woff2')) continue;
    copyFileSync(join(dist, 'fonts', f), join(dest, 'fonts', f));
    bytes += statSync(join(dest, 'fonts', f)).size;
    n++;
  }
  console.log(`katex        ${n} font files, ${(bytes / 1024).toFixed(0)} KB + ${(css.length / 1024).toFixed(0)} KB css`);
}

// ---------------------------------------------------------------------------
// 3. Render the page
// ---------------------------------------------------------------------------

{
  let html = readFileSync(join(SITE, 'index.src.html'), 'utf8');
  let count = 0;

  const render = (tex, display) => {
    count++;
    return katex.renderToString(decode(tex), {
      displayMode: display,
      throwOnError: true,
      output: 'htmlAndMathml',
      strict: 'ignore',
    });
  };

  // $$ … $$ first, so that the inline pass cannot bite into a display block.
  html = html.replace(/\$\$([\s\S]+?)\$\$/g, (_, tex) => render(tex, true));
  html = html.replace(/\\\(([\s\S]+?)\\\)/g, (_, tex) => render(tex, false));

  writeFileSync(join(SITE, 'index.html'), html);
  console.log(`index.html   ${count} expressions rendered, ${(html.length / 1024).toFixed(0)} KB`);
}

// The source file is HTML, so a few TeX-hostile entities have to come back.
function decode(s) {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"');
}
